# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapestryPlugin
                                 A QGIS plugin
 This plugin adds productivity tools to QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mike McPartland
        email                : michael.mcpartland@williamslea.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    QCoreApplication,
    Qt,
    QTimer,
    QVariant,
    QMetaObject,
    Q_ARG,
)
from qgis.PyQt.QtGui import QIcon, QFont, QColor
from qgis.PyQt.QtWidgets import QAction, QDockWidget, QToolButton
from qgis.core import QgsVectorLayer, QgsMapLayer, QgsProject, QgsAuxiliaryLayer
from qgis.PyQt import sip
from qgis.utils import iface
from PyQt5.QtCore import QMetaType
try:
    from qgis.gui import QgsMapToolPan, QgsMapToolSelectFeatures
except ImportError:
    QgsMapToolPan = None
    QgsMapToolSelectFeatures = None
from qgis import processing
import urllib.request
import zipfile
import os.path
import os
import requests
from urllib.parse import urlparse
from qgis.core import (
    QgsSimpleLineSymbolLayer,
    QgsSimpleFillSymbolLayer,
    QgsPalLayerSettings,
    QgsVectorLayerSimpleLabeling,
    QgsRuleBasedLabeling,
    QgsTextFormat,
    QgsField,
    QgsRenderContext,
    Qgis,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsCoordinateTransform,
)
from .geocodery import MapTilerGeocoder
from .resources import *
from .map_weaver_dockwidget import MapestryPluginDockWidget
from .marker_shape_combo import coerce_marker_shape_for_setshape
from .new_map_dialog import NewMapDialog
from .point_map_dialog import PointMapDialog


class MapestryPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):    

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MapestryPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.pluginIsActive = False
        self.dockwidget = None
        self.iface = iface
        self.toolbar = None
        self.button = None
        self.action = None
        self.button_action = None
        self.buttons_connected = False
        self._format_auto_apply_wired = False
        self.dock_width = 420
        self._new_map_dialog = None
        self._point_map_dialog = None
        self._geocode_color_widget = None
        self.geocoder = None
        self._route_connections_host = None
        self._move_label_highlight_wired = False

    def tr(self, message):
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MapestryPlugin', message)

    def _library_folder(self):
        """Local shapefile library (Library tab datasets)."""
        return os.path.join(self.plugin_dir, "library")

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, "graphics", "mapicon.png")

        # Keep a menu action, and use a real tool button on the toolbar
        # so we can force icon + text rendering.
        self.action = QAction(QIcon(icon_path), self.tr("Mapestry"), self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu(self.tr("&Mapestry"), self.action)
        
        plugin_toolbar = self.iface.pluginToolBar()
        self.button = QToolButton(plugin_toolbar)
        self.button.setIcon(QIcon(icon_path))
        self.button.setText(self.tr("Mapestry"))
        self.button.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.button.clicked.connect(self.run)
        self.button_action = plugin_toolbar.addWidget(self.button)
        

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING MapestryPlugin"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self._unwire_move_label_mode_highlight()
        self.buttons_connected = False
        self._format_auto_apply_wired = False
        self.geocoder = None
        if getattr(self, "_point_map_dialog", None) is not None:
            try:
                self._point_map_dialog.close()
            except Exception:
                pass
            self._point_map_dialog = None
        if self.action is not None:
            self.iface.removePluginMenu(self.tr("&Mapestry"), self.action)
            self.action = None
        if self.button_action is not None:
            plugin_toolbar = self.iface.pluginToolBar()
            plugin_toolbar.removeAction(self.button_action)
            self.button_action = None
        if self.button is not None:
            self.button.deleteLater()
            self.button = None
       

    #--------------------------------------------------------------------------



    def run(self):
        """Run method that loads and starts the plugin"""
        self.pluginIsActive = True

        if self.dockwidget is None:
            # Create once and keep reusing this same dockwidget instance.
            self.dockwidget = MapestryPluginDockWidget()
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.dockwidget.visibilityChanged.connect(self._onDockVisibilityChanged)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)

        self.dockwidget.show()
        self.dockwidget.raise_()
        self.dockwidget.activateWindow()
        self._applyDockWidth()
        # Re-apply after QGIS splitter/layout settles.
        QTimer.singleShot(0, self._applyDockWidth)
        QTimer.singleShot(100, self._applyDockWidth)
        self.addButtons()
        self.dockwidget.refreshLibraryBasemapsList(self._library_folder())
        QTimer.singleShot(0, self._refresh_cmb_border_style)

            
    def addButtons(self):
        if self.buttons_connected:
            return

        #self.dockwidget.ButtonTwo.clicked.connect(self.removeBorders)
        #self.dockwidget.btnAddMap.clicked.connect(lambda: self.amerge_all_shapes("US Counties 2024"))
        #self.dockwidget.btnAddMap.clicked.connect(lambda: self.load_online_shapefile("US Counties 2024", r"C\Temp\mapestry", "downloaded_map"))
        self.dockwidget.btnAddMap.clicked.connect(self.LoadAnyFileAsLayer)
        #self.dockwidget.BorderPlus.clicked.connect(self.SetSymbolBorders)
        self.dockwidget.btnAddLabels.clicked.connect(self.AddLabels)
        self.dockwidget.btnApplyFormat.clicked.connect(self.SetSymbolFormat)
        self._wire_format_auto_apply()
        self.dockwidget.routeConnectionsDialogRequested.connect(self.openRouteConnectionsDialog)
        self.dockwidget.locationPlotToolRequested.connect(self.openPointMapDialog)
        self.dockwidget.pbnCenterView.clicked.connect(self.CenterMapOnSelectedLayerGeometryCenter)
        self.dockwidget.btnNewMap.clicked.connect(self.openNewMapDialog)
        self.dockwidget.pbnMoreFormat.clicked.connect(self.openLayerSymbologyProperties)
        self.dockwidget.libraryBasemapPathChosen.connect(self.loadBasemapFromFile)
        ml = getattr(self.dockwidget, "pbnMoveLabels", None)
        if ml is not None:
            ml.clicked.connect(self._on_move_labels_clicked)
        lf = getattr(self.dockwidget, "cmbLabelField", None)
        if lf is not None:
            lf.activated.connect(self._on_label_field_activated)
        fcb_labels = getattr(self.dockwidget, "fcbMapLabels", None)
        if fcb_labels is not None:
            fcb_labels.currentFontChanged.connect(self._on_map_label_font_changed)
        for biu_name in ("pushButton", "pushButton_2", "pushButton_3"):
            biu = getattr(self.dockwidget, biu_name, None)
            if biu is not None:
                biu.toggled.connect(self._on_map_label_biu_toggled)
        pan_b = getattr(self.dockwidget, "pbnPanMap", None)
        if pan_b is not None:
            pan_b.setCheckable(True)
            pan_b.setToolTip(self.tr("Pan map (same as the main Pan tool)"))
            pan_b.toggled.connect(self._on_pbn_pan_toggled)
        sel_b = getattr(self.dockwidget, "pbnSelectMap", None)
        if sel_b is not None:
            sel_b.setCheckable(True)
            sel_b.setToolTip(self.tr("Select features (same as the main Select Features tool)"))
            sel_b.toggled.connect(self._on_pbn_select_toggled)
        self.buttons_connected = True
        self._wire_move_label_mode_highlight()

    def _wire_move_label_mode_highlight(self):
        """Highlight pbnMoveLabels while the canvas Move Label map tool is active (any activation path)."""
        if self._move_label_highlight_wired:
            return
        canvas = self.iface.mapCanvas() if self.iface else None
        if canvas is None:
            return
        # QgsMapCanvas uses mapToolSet (QGIS API); some builds only expose mapToolChanged.
        handler = self._on_canvas_map_tool_changed_move_highlight
        if hasattr(canvas, "mapToolSet"):
            canvas.mapToolSet.connect(handler)
        elif hasattr(canvas, "mapToolChanged"):
            canvas.mapToolChanged.connect(handler)
        else:
            self._move_label_highlight_wired = False
            return
        self._move_label_highlight_wired = True
        self._on_canvas_map_tool_changed_move_highlight()

    def _unwire_move_label_mode_highlight(self):
        if not self._move_label_highlight_wired:
            return
        self._move_label_highlight_wired = False
        canvas = self.iface.mapCanvas() if self.iface else None
        if canvas is None:
            return
        handler = self._on_canvas_map_tool_changed_move_highlight
        for name in ("mapToolSet", "mapToolChanged"):
            if hasattr(canvas, name):
                try:
                    getattr(canvas, name).disconnect(handler)
                except (TypeError, RuntimeError):
                    pass

    def _on_canvas_map_tool_changed_move_highlight(self, new_tool=None, old_tool=None):
        tool = new_tool
        if tool is None and self.iface is not None and self.iface.mapCanvas() is not None:
            tool = self.iface.mapCanvas().mapTool()
        self._apply_move_label_button_highlight(tool)
        self._sync_pan_select_buttons_from_canvas_tool(tool)

    @staticmethod
    def _tool_action_object_name(tool):
        if tool is None:
            return ""
        fn = getattr(tool, "action", None)
        if not callable(fn):
            return ""
        try:
            a = fn()
        except Exception:
            return ""
        if a is None:
            return ""
        try:
            return str(a.objectName() or "")
        except Exception:
            return ""

    @classmethod
    def _map_tool_is_pan_tool(cls, tool):
        if tool is None:
            return False
        if QgsMapToolPan is not None:
            try:
                if isinstance(tool, QgsMapToolPan):
                    return True
            except Exception:
                pass
        on = cls._tool_action_object_name(tool)
        return on in ("mActionPan", "mActionTouchPan")

    @classmethod
    def _map_tool_is_select_features_tool(cls, tool):
        if tool is None:
            return False
        if QgsMapToolSelectFeatures is not None:
            try:
                if isinstance(tool, QgsMapToolSelectFeatures):
                    return True
            except Exception:
                pass
        on = cls._tool_action_object_name(tool)
        return on in (
            "mActionSelectFeatures",
            "mActionSelectRectangle",
            "mActionSelectPolygon",
            "mActionSelectFreehand",
            "mActionSelectRadius",
        )

    def _sync_pan_select_buttons_from_canvas_tool(self, tool):
        """Reflect canvas map tool on checkable Pan / Select buttons (Move Label clears both)."""
        dw = self.dockwidget
        if dw is None or sip.isdeleted(dw):
            return
        pan_btn = getattr(dw, "pbnPanMap", None)
        sel_btn = getattr(dw, "pbnSelectMap", None)
        if pan_btn is None or sel_btn is None:
            return
        if sip.isdeleted(pan_btn) or sip.isdeleted(sel_btn):
            return
        if self._map_tool_is_move_label_tool(tool):
            pan_on, sel_on = False, False
        elif self._map_tool_is_pan_tool(tool):
            pan_on, sel_on = True, False
        elif self._map_tool_is_select_features_tool(tool):
            pan_on, sel_on = False, True
        else:
            pan_on, sel_on = False, False
        pan_btn.blockSignals(True)
        sel_btn.blockSignals(True)
        try:
            pan_btn.setChecked(bool(pan_on))
            sel_btn.setChecked(bool(sel_on))
        finally:
            pan_btn.blockSignals(False)
            sel_btn.blockSignals(False)

    def _on_pbn_pan_toggled(self, checked):
        """Exclusive with Select: checked → Pan tool; unchecked → Select tool."""
        dw = self.dockwidget
        if dw is None:
            return
        pan = getattr(dw, "pbnPanMap", None)
        sel = getattr(dw, "pbnSelectMap", None)
        if pan is None:
            return
        if not checked:
            self._exclusive_check_select_when_pan_off(sel)
            self._activate_select_features_tool()
            return
        if sel is not None:
            sel.blockSignals(True)
            sel.setChecked(False)
            sel.blockSignals(False)
        self._activate_pan_map_tool()

    def _on_pbn_select_toggled(self, checked):
        """Exclusive with Pan: checked → Select tool; unchecked → Pan tool."""
        dw = self.dockwidget
        if dw is None:
            return
        pan = getattr(dw, "pbnPanMap", None)
        sel = getattr(dw, "pbnSelectMap", None)
        if sel is None:
            return
        if not checked:
            self._exclusive_check_pan_when_select_off(pan)
            self._activate_pan_map_tool()
            return
        if pan is not None:
            pan.blockSignals(True)
            pan.setChecked(False)
            pan.blockSignals(False)
        self._activate_select_features_tool()

    @staticmethod
    def _exclusive_check_select_when_pan_off(sel_btn):
        if sel_btn is None or sip.isdeleted(sel_btn):
            return
        sel_btn.blockSignals(True)
        if not sel_btn.isChecked():
            sel_btn.setChecked(True)
        sel_btn.blockSignals(False)

    @staticmethod
    def _exclusive_check_pan_when_select_off(pan_btn):
        if pan_btn is None or sip.isdeleted(pan_btn):
            return
        pan_btn.blockSignals(True)
        if not pan_btn.isChecked():
            pan_btn.setChecked(True)
        pan_btn.blockSignals(False)

    def _activate_select_features_tool(self):
        if iface is None:
            return
        fn = getattr(iface, "actionSelect", None)
        if callable(fn):
            act = fn()
            if act is not None:
                act.trigger()
                return
        mw = iface.mainWindow()
        if mw is not None:
            for a in mw.findChildren(QAction):
                if a.objectName() == "mActionSelectFeatures":
                    a.trigger()
                    return

    def _apply_move_label_button_highlight(self, tool):
        dw = self.dockwidget
        if dw is None:
            return
        btn = getattr(dw, "pbnMoveLabels", None)
        if btn is None:
            return
        active = self._map_tool_is_move_label_tool(tool)
        btn.setProperty("moveLabelMode", active)
        st = btn.style()
        if st is not None:
            st.unpolish(btn)
            st.polish(btn)
        btn.update()

    def _on_move_labels_clicked(self):
        """Same as the main-window Labels toolbar “Move a Label, Diagram or Callout” tool."""
        mw = iface.mainWindow() if iface is not None else None
        if mw is None:
            return
        act = mw.findChild(QAction, "mActionMoveLabel")
        if act is None:
            for a in mw.findChildren(QAction):
                if a.objectName() == "mActionMoveLabel":
                    act = a
                    break
        if act is None:
            self.iface.messageBar().pushMessage(
                self.tr("Move labels"),
                self.tr(
                    "Could not find QGIS’s Move Label action. Turn on the Labels toolbar "
                    "(View → Toolbars → Labels Toolbar), then try again."
                ),
                level=Qgis.Warning,
            )
            return

        layer = self._vector_layer_for_label_target()
        if self._should_exit_move_label_mode(layer):
            self._activate_pan_map_tool()
            return

        dw = self.dockwidget
        if layer is not None and iface is not None:
            iface.setActiveLayer(layer)

        need_enable = (
            layer is not None
            and dw is not None
            and hasattr(layer, "labelsEnabled")
            and not layer.labelsEnabled()
        )
        if need_enable:
            dw._toggleLayerLabelsFromRow(layer)
            if iface is not None:
                iface.setActiveLayer(layer)

        if layer is not None:
            self._ensure_auxiliary_storage_for_move_labels(layer)
            self._refresh_move_label_context(layer)

        if self._invoke_move_label_map_tool(mw, layer):
            return
        if act is not None and act.isEnabled():
            act.trigger()
            return

        QTimer.singleShot(0, lambda: self._try_trigger_move_label_action(mw, act, layer))

    @staticmethod
    def _map_tool_is_move_label_tool(tool):
        if tool is None:
            return False
        fn = getattr(tool, "action", None)
        if not callable(fn):
            return False
        a = fn()
        return a is not None and a.objectName() == "mActionMoveLabel"

    def _should_exit_move_label_mode(self, layer):
        """True when this click should leave move-label mode (Pan), not start setup for a new target."""
        if iface is None:
            return False
        canvas = iface.mapCanvas()
        if canvas is None:
            return False
        if not self._map_tool_is_move_label_tool(canvas.mapTool()):
            return False
        if layer is None or sip.isdeleted(layer) or not isinstance(layer, QgsVectorLayer):
            return False
        if iface.activeLayer() is not layer:
            return False
        if not hasattr(layer, "labelsEnabled") or not layer.labelsEnabled():
            return False
        return True

    def _activate_pan_map_tool(self):
        if iface is None:
            return
        pan_act = getattr(iface, "actionPan", None)
        if callable(pan_act):
            a = pan_act()
            if a is not None:
                a.trigger()
                return
        mw = iface.mainWindow()
        if mw is not None:
            pfn = getattr(mw, "pan", None)
            if callable(pfn):
                pfn()

    def _refresh_move_label_context(self, layer):
        """Notify QGIS that labeling/aux changed so toolbars refresh (Properties OK does this implicitly)."""
        if layer is None or sip.isdeleted(layer):
            return
        es = getattr(layer, "emitStyleChanged", None)
        if callable(es):
            es()
        if iface is not None:
            iface.setActiveLayer(layer)
        QCoreApplication.processEvents()
        mw = iface.mainWindow() if iface is not None else None
        self._sync_builtin_label_toolbar(mw, layer)

    def _sync_builtin_label_toolbar(self, mw, layer):
        """Re-run QgisApp’s layer-action refresh so built-in Labels toolbar enables (same as Layer Properties OK)."""
        if mw is None or layer is None or sip.isdeleted(layer):
            return
        try:
            QMetaObject.invokeMethod(
                mw,
                "activateDeactivateLayerRelatedActions",
                Qt.DirectConnection,
                Q_ARG(QgsMapLayer, layer),
            )
        except (TypeError, RuntimeError, AttributeError):
            try:
                QMetaObject.invokeMethod(
                    mw, "updateLabelToolButtons", Qt.DirectConnection
                )
            except (TypeError, RuntimeError, AttributeError):
                pass
        try:
            from qgis.gui import QgsLayerStylingWidget

            for w in mw.findChildren(QgsLayerStylingWidget):
                sig = getattr(w, "styleChanged", None)
                if sig is not None and hasattr(sig, "emit"):
                    sig.emit()
        except (ImportError, TypeError, RuntimeError, AttributeError):
            pass
        QCoreApplication.processEvents()

    @staticmethod
    def _invoke_move_label_map_tool(mw, layer):
        """Call QgisApp.moveLabel() — same as the Labels toolbar but does not depend on QAction.isEnabled()."""
        if mw is None or layer is None or sip.isdeleted(layer):
            return False
        if not isinstance(layer, QgsVectorLayer):
            return False
        if not hasattr(layer, "labelsEnabled") or not layer.labelsEnabled():
            return False
        fn = getattr(mw, "moveLabel", None)
        if not callable(fn):
            return False
        fn()
        return True

    def _try_trigger_move_label_action(self, mw, act, layer=None):
        if self._should_exit_move_label_mode(layer):
            self._activate_pan_map_tool()
            return
        if layer is not None:
            self._ensure_auxiliary_storage_for_move_labels(layer)
            self._refresh_move_label_context(layer)
        if self._invoke_move_label_map_tool(mw, layer):
            return
        if act is not None and act.isEnabled():
            act.trigger()
            return
        self.iface.messageBar().pushMessage(
            self.tr("Move labels"),
            self.tr(
                "That tool is not active yet. Select a vector layer with labeling (or diagrams/callouts) enabled."
            ),
            level=Qgis.Info,
        )

    @staticmethod
    def _guess_auxiliary_primary_key_field_index(layer):
        """Pick a join field for auxiliary storage (moved labels); prefer provider PK then common id columns."""
        if layer is None or sip.isdeleted(layer) or not isinstance(layer, QgsVectorLayer):
            return -1
        fields = layer.fields()
        n = fields.count()
        if n <= 0:
            return -1
        try:
            pk_attrs = layer.primaryKeyAttributes()
        except (AttributeError, TypeError):
            pk_attrs = []
        if pk_attrs:
            idx = int(pk_attrs[0])
            if 0 <= idx < n:
                return idx
        preferred = (
            "fid",
            "OBJECTID",
            "OBJECTID_1",
            "GEOID",
            "OGR_FID",
            "ogc_fid",
            "gml_id",
            "id",
            "name",
        )
        lower_to_idx = {}
        for i in range(n):
            nm = fields.at(i).name()
            if nm:
                lower_to_idx[nm.lower()] = i
        for cand in preferred:
            j = lower_to_idx.get(cand.lower())
            if j is not None:
                return j
        return 0

    def _auxiliary_join_field_ready(self, layer):
        if layer is None or sip.isdeleted(layer) or not isinstance(layer, QgsVectorLayer):
            return False
        aux = layer.auxiliaryLayer()
        if aux is None:
            return False
        ji = aux.joinInfo()
        if ji is None:
            return False
        tfn = ji.targetFieldName()
        return bool(tfn and str(tfn).strip())

    @staticmethod
    def _pal_position_xy_properties_for_auxiliary():
        """QgsPalLayerSettings.Property entries for label X/Y (required for Move Label + auxiliary)."""
        p = QgsPalLayerSettings
        prop = getattr(p, "Property", None)
        if prop is not None:
            px = getattr(prop, "PositionX", None)
            py = getattr(prop, "PositionY", None)
            if px is not None and py is not None:
                return px, py
        px = getattr(p, "PositionX", None)
        py = getattr(p, "PositionY", None)
        if px is not None and py is not None:
            return px, py
        return None, None

    def _ensure_pal_auxiliary_position_properties(self, layer):
        """Wire PositionX/Y to auxiliary fields (same as Labels tab applying data-defined positions)."""
        if layer is None or sip.isdeleted(layer) or not isinstance(layer, QgsVectorLayer):
            return
        if not layer.labelsEnabled() or layer.labeling() is None or layer.auxiliaryLayer() is None:
            return
        lab = layer.labeling()
        if MapestryPluginDockWidget._is_rule_based_labeling(lab):
            return
        px, py = self._pal_position_xy_properties_for_auxiliary()
        if px is None or py is None:
            return
        try:
            QgsAuxiliaryLayer.createProperty(px, layer, True)
            QgsAuxiliaryLayer.createProperty(py, layer, True)
        except (TypeError, AttributeError):
            try:
                QgsAuxiliaryLayer.createProperty(px, layer)
                QgsAuxiliaryLayer.createProperty(py, layer)
            except (TypeError, AttributeError):
                return
        layer.triggerRepaint()

    def _ensure_auxiliary_storage_for_move_labels(self, layer):
        """Ensure auxiliary DB join + PAL PositionX/Y fields so Move Label works without opening Properties."""
        if layer is None or sip.isdeleted(layer) or not isinstance(layer, QgsVectorLayer):
            return
        if not self._auxiliary_join_field_ready(layer):
            storage = QgsProject.instance().auxiliaryStorage()
            if storage is None or not storage.isValid():
                return
            idx = self._guess_auxiliary_primary_key_field_index(layer)
            if idx < 0:
                return
            pkf = layer.fields().field(idx)
            al = storage.createAuxiliaryLayer(pkf, layer)
            if al is None:
                return
            if hasattr(al, "isValid") and callable(al.isValid) and not al.isValid():
                return
            layer.setAuxiliaryLayer(al)
        self._ensure_pal_auxiliary_position_properties(layer)

    def _vector_layer_for_label_target(self):
        """Vector layer targeted by Format tab selection (labels are independent of symbol renderer)."""
        dw = self.dockwidget
        if dw is None:
            return None
        layer = dw._layerTargetForFormatTab()
        if layer is None:
            return None
        if sip.isdeleted(layer):
            return None
        if layer.type() != QgsMapLayer.VectorLayer or not isinstance(layer, QgsVectorLayer):
            return None
        return layer

    def _on_label_field_activated(self, index):
        """Set single-label Value column (QgsPalLayerSettings.fieldName) to the chosen attribute."""
        if self.dockwidget is None:
            return
        cmb = getattr(self.dockwidget, "cmbLabelField", None)
        if cmb is None or index < 0:
            return
        name = cmb.itemData(index)
        if name in (None, ""):
            name = cmb.itemText(index)
        if not name:
            return
        layer = self._vector_layer_for_label_target()
        if layer is None:
            return
        lab = layer.labeling() if hasattr(layer, "labeling") else None
        if MapestryPluginDockWidget._is_rule_based_labeling(lab):
            self.iface.messageBar().pushMessage(
                self.tr("Labels"),
                self.tr("Rule-based labels must be changed in Layer Properties."),
                level=Qgis.Info,
            )
            return
        st0 = MapestryPluginDockWidget._pal_settings_from_layer_labeling(layer)
        if st0 is not None:
            try:
                s = QgsPalLayerSettings(st0)
            except Exception:
                s = st0
        else:
            s = QgsPalLayerSettings()
            s.enabled = True
            tf = QgsTextFormat()
            tf.setFont(QFont("Open Sans", 10))
            tf.setSize(10)
            s.setFormat(tf)
            s.placement = QgsPalLayerSettings.AroundPoint
        s.fieldName = name
        try:
            s.isExpression = False
        except Exception:
            fn = getattr(s, "setIsExpression", None)
            if callable(fn):
                fn(False)
        layer_id = layer.id()
        dw = self.dockwidget
        canvas = iface.mapCanvas() if iface is not None else None
        if canvas is not None:
            canvas.freeze(True)
        try:
            layer.setLabeling(QgsVectorLayerSimpleLabeling(s))
            if hasattr(layer, "labelsEnabled") and not layer.labelsEnabled():
                layer.setLabelsEnabled(True)
        finally:
            if canvas is not None:
                canvas.freeze(False)
        layer.triggerRepaint()
        if iface.layerTreeView() is not None:
            iface.layerTreeView().refreshLayerSymbology(layer_id)
        canon = MapestryPluginDockWidget._canonical_field_name(layer, name) or name
        dw._last_known_label_field_by_layer_id[layer_id] = str(canon)

        def _resync_label_combo():
            lyr = QgsProject.instance().mapLayer(layer_id)
            if lyr is None or dw is None or sip.isdeleted(dw):
                return
            dw._syncLabelFieldComboFromLayer(lyr)

        QTimer.singleShot(0, _resync_label_combo)

    def _on_map_label_font_changed(self, font):
        """Apply QFontComboBox family to layer QgsTextFormat (keeps label size/units)."""
        if self.dockwidget is None:
            return
        layer = self._vector_layer_for_label_target()
        if layer is None:
            return
        lab = layer.labeling() if hasattr(layer, "labeling") else None
        if MapestryPluginDockWidget._is_rule_based_labeling(lab):
            self.iface.messageBar().pushMessage(
                self.tr("Labels"),
                self.tr("Rule-based labels must be changed in Layer Properties."),
                level=Qgis.Info,
            )
            return
        st0 = MapestryPluginDockWidget._pal_settings_from_layer_labeling(layer)
        if st0 is None:
            return
        try:
            s = QgsPalLayerSettings(st0)
        except Exception:
            s = st0
        try:
            tf = QgsTextFormat(s.format())
        except Exception:
            return
        qf = QFont(tf.font())
        qf.setFamily(font.family())
        tf.setFont(qf)
        s.setFormat(tf)
        layer_id = layer.id()
        dw = self.dockwidget
        canvas = iface.mapCanvas() if iface is not None else None
        if canvas is not None:
            canvas.freeze(True)
        try:
            layer.setLabeling(QgsVectorLayerSimpleLabeling(s))
            if hasattr(layer, "labelsEnabled") and not layer.labelsEnabled():
                layer.setLabelsEnabled(True)
        finally:
            if canvas is not None:
                canvas.freeze(False)
        layer.triggerRepaint()
        if iface.layerTreeView() is not None:
            iface.layerTreeView().refreshLayerSymbology(layer_id)

        def _resync_font_combo():
            lyr = QgsProject.instance().mapLayer(layer_id)
            if lyr is None or dw is None or sip.isdeleted(dw):
                return
            dw._syncLabelFontComboFromLayer(lyr)

        QTimer.singleShot(0, _resync_font_combo)

    def _on_map_label_biu_toggled(self, _checked=False):
        """Bold / italic / underline toggles → QgsTextFormat font (single-label layers)."""
        if self.dockwidget is None:
            return
        dw = self.dockwidget
        btn_b = getattr(dw, "pushButton", None)
        btn_i = getattr(dw, "pushButton_2", None)
        btn_u = getattr(dw, "pushButton_3", None)
        layer = self._vector_layer_for_label_target()
        if layer is None:
            return
        lab = layer.labeling() if hasattr(layer, "labeling") else None
        if MapestryPluginDockWidget._is_rule_based_labeling(lab):
            self.iface.messageBar().pushMessage(
                self.tr("Labels"),
                self.tr("Rule-based labels must be changed in Layer Properties."),
                level=Qgis.Info,
            )
            return
        st0 = MapestryPluginDockWidget._pal_settings_from_layer_labeling(layer)
        if st0 is None:
            return
        try:
            s = QgsPalLayerSettings(st0)
        except Exception:
            s = st0
        try:
            tf = QgsTextFormat(s.format())
        except Exception:
            return
        qf = QFont(tf.font())
        if btn_b is not None:
            qf.setBold(btn_b.isChecked())
        if btn_i is not None:
            qf.setItalic(btn_i.isChecked())
        if btn_u is not None:
            qf.setUnderline(btn_u.isChecked())
        tf.setFont(qf)
        s.setFormat(tf)
        layer_id = layer.id()
        canvas = iface.mapCanvas() if iface is not None else None
        if canvas is not None:
            canvas.freeze(True)
        try:
            layer.setLabeling(QgsVectorLayerSimpleLabeling(s))
            if hasattr(layer, "labelsEnabled") and not layer.labelsEnabled():
                layer.setLabelsEnabled(True)
        finally:
            if canvas is not None:
                canvas.freeze(False)
        layer.triggerRepaint()
        if iface.layerTreeView() is not None:
            iface.layerTreeView().refreshLayerSymbology(layer_id)

        def _resync_biu():
            lyr = QgsProject.instance().mapLayer(layer_id)
            if lyr is None or dw is None or sip.isdeleted(dw):
                return
            dw._syncLabelBiuButtonsFromLayer(lyr)

        QTimer.singleShot(0, _resync_biu)

    def _wire_format_auto_apply(self):
        """Apply Format tab symbology as the user edits (Apply button remains as a manual refresh)."""
        if getattr(self, "_format_auto_apply_wired", False):
            return
        dw = self.dockwidget
        if dw is None:
            return

        btn_fill = getattr(dw, "plhQWcolorbutton02", None)
        if btn_fill is not None:
            btn_fill.colorChanged.connect(self.SetSymbolFill)

        btn_stroke = getattr(dw, "plhQWcolorbutton", None)
        if btn_stroke is not None:
            btn_stroke.colorChanged.connect(self.SetSymbolBorders)

        cmb_style = getattr(dw, "cmbBorderStyle", None)
        if cmb_style is not None:
            # activated = user picked from list (avoids firing on programmatic sync)
            cmb_style.activated.connect(lambda *_: self.SetSymbolBorders())

        cmb_shape = getattr(dw, "cmbMarkerShape", None)
        if cmb_shape is not None:
            cmb_shape.activated.connect(lambda *_: self.SetSymbolMarkerShape())
            # MarkerShapeCombo uses a custom grid popup; setCurrentIndex may be the only reliable signal on older PyQt/QGIS.
            cmb_shape.currentIndexChanged.connect(self._on_marker_shape_combo_index_changed)

        for attr, slot in (
            ("dsbBorderWeight", self._on_border_weight_changed),
            ("dsbBorderWeight_5", self.SetSymbolMarkerSize),
        ):
            sp = getattr(dw, attr, None)
            if sp is None:
                continue
            try:
                sp.setKeyboardTracking(False)
            except Exception:
                pass
            # keyboardTracking off: valueChanged on step buttons, Enter, and focus-out commit (avoids per-keypress apply).
            sp.valueChanged.connect(slot)

        for rad_name in ("radDashLine", "radSolidLine"):
            rad = getattr(dw, rad_name, None)
            if rad is not None:
                rad.toggled.connect(lambda *_: self.SetSymbolBorders())

        self._format_auto_apply_wired = True

    def _refresh_cmb_border_style(self):
        if self.dockwidget is None:
            return
        combo = getattr(self.dockwidget, "cmbBorderStyle", None)
        if combo is not None and hasattr(combo, "rebuild_line_items"):
            combo.rebuild_line_items()

    def openNewMapDialog(self):
        if self._new_map_dialog is None:
            self._new_map_dialog = NewMapDialog(self.iface.mainWindow(), plugin=self)
        self._new_map_dialog.show()
        self._new_map_dialog.raise_()
        self._new_map_dialog.activateWindow()

    def _onDockVisibilityChanged(self, visible):
        if visible:
            self._hideBuiltInLayerPanel()
            self._applyDockWidth()
            QTimer.singleShot(0, self._hideBuiltInLayerPanel)
            QTimer.singleShot(0, self._applyDockWidth)
            QTimer.singleShot(100, self._hideBuiltInLayerPanel)
            QTimer.singleShot(100, self._applyDockWidth)

    def _hideBuiltInLayerPanel(self):
        """Hide QGIS built-in layer panel dock if currently visible."""
        main_layer_view = self.iface.layerTreeView() if self.iface is not None else None
        if main_layer_view is None:
            return

        layer_dock = main_layer_view.parentWidget()
        while layer_dock is not None and not isinstance(layer_dock, QDockWidget):
            layer_dock = layer_dock.parentWidget()

        if layer_dock is not None and layer_dock.isVisible():
            layer_dock.hide()

    def _applyDockWidth(self):
        if self.dockwidget is None:
            return
        self.dockwidget.setMinimumWidth(self.dock_width)
        self.iface.mainWindow().resizeDocks([self.dockwidget], [self.dock_width], Qt.Horizontal)

    def CenterMapOnSelectedLayerGeometryCenter(self):
        """Center map canvas on densest vertex area of selected layer."""
        layer = None
        if self.dockwidget is not None and hasattr(self.dockwidget, "selectedLayerFromPanel"):
            layer = self.dockwidget.selectedLayerFromPanel()
        if layer is None:
            self.iface.messageBar().pushMessage("Warning", "No layer available in panel.", level=Qgis.Warning)
            return

        extent = layer.extent()
        if extent.isEmpty():
            self.iface.messageBar().pushMessage(
                "Warning",
                f"Layer '{layer.name()}' has no geometry extent.",
                level=Qgis.Warning
            )
            return

        target_center = self._densestLayerVertexCenter(layer)
        if target_center is None:
            target_center = extent.center()

        canvas = self.iface.mapCanvas()
        if hasattr(layer, "crs") and layer.crs().isValid():
            try:
                xform = QgsCoordinateTransform(
                    layer.crs(), canvas.mapSettings().destinationCrs(), QgsProject.instance()
                )
                target_center = xform.transform(target_center)
            except Exception:
                # Keep fallback in layer coordinates if transform fails.
                pass

        canvas = self.iface.mapCanvas()
        canvas.setCenter(target_center)
        canvas.refresh()

    def openLayerSymbologyProperties(self):
        """Open Layer Properties on the Symbology tab for the layer selected in the dock panel."""
        layer = None
        if self.dockwidget is not None and hasattr(self.dockwidget, "selectedLayerFromPanel"):
            layer = self.dockwidget.selectedLayerFromPanel()
        if layer is None:
            self.iface.messageBar().pushMessage(
                "Map Weaver",
                "Select a layer in the panel first.",
                level=Qgis.Warning,
            )
            return
        try:
            from qgis.PyQt import sip

            if sip.isdeleted(layer):
                return
        except Exception:
            pass

        # QGIS names the Symbology page key mOptsPage_Style (see QgisInterface::showLayerProperties).
        page = "mOptsPage_Style"
        try:
            from qgis.core import QgsPointCloudLayer

            if isinstance(layer, QgsPointCloudLayer):
                page = "mOptsPage_Rendering"
        except ImportError:
            pass

        self.iface.showLayerProperties(layer, page)

    def _densestLayerVertexCenter(self, layer):
        """Return center point of the densest vertex bin."""
        if not isinstance(layer, QgsVectorLayer):
            return None
        extent = layer.extent()
        if extent is None:
            return None

        try:
            xmin = float(extent.xMinimum())
            ymin = float(extent.yMinimum())
            w = float(extent.width())
            h = float(extent.height())
        except Exception:
            # Some SIP bindings can return unexpected method descriptors in edge cases.
            # Fall back to safe centering behavior instead of crashing.
            return None

        if w <= 0 or h <= 0:
            return None

        cols = 24
        rows = 24
        counts = [[0 for _ in range(cols)] for _ in range(rows)]
        max_vertices = 50000
        seen = 0

        for f in layer.getFeatures():
            g = f.geometry()
            if g is None or g.isEmpty():
                continue
            for v in g.vertices():
                if seen >= max_vertices:
                    break
                x = v.x()
                y = v.y()
                cx = int((x - xmin) / w * cols)
                cy = int((y - ymin) / h * rows)
                if cx < 0:
                    cx = 0
                elif cx >= cols:
                    cx = cols - 1
                if cy < 0:
                    cy = 0
                elif cy >= rows:
                    cy = rows - 1
                counts[cy][cx] += 1
                seen += 1
            if seen >= max_vertices:
                break

        if seen == 0:
            return None

        best_x = 0
        best_y = 0
        best = -1
        for r in range(rows):
            for c in range(cols):
                if counts[r][c] > best:
                    best = counts[r][c]
                    best_x = c
                    best_y = r
        if best <= 0:
            return None

        center_x = xmin + (best_x + 0.5) * (w / cols)
        center_y = ymin + (best_y + 0.5) * (h / rows)
        return QgsPointXY(center_x, center_y)

    def _safeExtractZip(self, zip_path, extract_folder):
        """Extract ZIP while preventing path traversal (zip-slip)."""
        abs_target = os.path.abspath(extract_folder)
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            for member in zip_ref.infolist():
                member_path = os.path.abspath(os.path.join(abs_target, member.filename))
                if not (member_path == abs_target or member_path.startswith(abs_target + os.sep)):
                    raise ValueError(f"Unsafe path in zip: {member.filename}")
            zip_ref.extractall(abs_target)

    def _activeRenderableLayer(self):
        """Return active layer if it supports renderer/symbol operations."""
        layer = iface.activeLayer()
        if layer is None:
            iface.messageBar().pushMessage("Warning", "No active layer selected.", level=Qgis.Warning)
            return None
        if not hasattr(layer, "renderer") or layer.renderer() is None:
            iface.messageBar().pushMessage(
                "Warning", f"Layer '{layer.name()}' is not renderable.", level=Qgis.Warning
            )
            return None
        symbol = layer.renderer().symbol() if hasattr(layer.renderer(), "symbol") else None
        if symbol is None or symbol.symbolLayerCount() == 0:
            iface.messageBar().pushMessage(
                "Warning", f"Layer '{layer.name()}' has no editable symbol.", level=Qgis.Warning
            )
            return None
        return layer

    def _layerForFormatApply(self):
        """Layer targeted by the Format tab (embedded panel selection, then active layer)."""
        layer = None
        if self.dockwidget is not None and hasattr(self.dockwidget, "_layerTargetForFormatTab"):
            layer = self.dockwidget._layerTargetForFormatTab()
        if layer is None and self.iface is not None:
            layer = self.iface.activeLayer()
        if layer is None or not hasattr(layer, "renderer") or layer.renderer() is None:
            return None
        sym = MapestryPluginDockWidget._renderer_primary_symbol(layer)
        if sym is None or sym.symbolLayerCount() == 0:
            return None
        return layer

                                                   
    def getBasemap(self, path_to_shapefile):
            
        layer_name = self.FileNamePlain(path_to_shapefile)
        vlayer = QgsVectorLayer(path_to_shapefile, layer_name, "ogr")

        # 3. Check if the layer is valid and add it to the map
        if not vlayer.isValid():
            print("Layer failed to load! Check your file path.")
        else:
            QgsProject.instance().addMapLayer(vlayer)
            print(f"Successfully added: {layer_name}")

    def loadBasemapFromFile(self, file_path):
        """Load a local .shp or zipped shapefile (Library tab / library folder)."""
        file_path = os.path.normpath(os.path.abspath(file_path))
        if not os.path.isfile(file_path):
            self.iface.messageBar().pushMessage(
                "Warning", f"File not found: {file_path}", level=Qgis.Warning
            )
            return
        ext = os.path.splitext(file_path)[1].lower()
        if ext == ".shp":
            self.getBasemap(file_path)
            return
        if ext == ".zip":
            self._add_layer_from_local_shapefile_zip(file_path)
            return
        self.iface.messageBar().pushMessage(
            "Warning", f"Unsupported file type: {file_path}", level=Qgis.Warning
        )

    def _add_layer_from_local_shapefile_zip(self, zip_path):
        try:
            with zipfile.ZipFile(zip_path, "r") as zf:
                shp_names = [n for n in zf.namelist() if n.lower().endswith(".shp")]
        except zipfile.BadZipFile as e:
            self.iface.messageBar().pushMessage("Warning", f"Invalid zip: {e}", level=Qgis.Warning)
            return
        if not shp_names:
            self.iface.messageBar().pushMessage(
                "Warning", "No shapefile (.shp) found in zip.", level=Qgis.Warning
            )
            return
        shp_inner = sorted(shp_names)[0]
        znorm = zip_path.replace("\\", "/")
        vsipath = "/vsizip/" + znorm + "/" + shp_inner.replace("\\", "/")
        layer_name = self.FileNamePlain(os.path.basename(shp_inner))
        vlayer = QgsVectorLayer(vsipath, layer_name, "ogr")
        if vlayer.isValid():
            QgsProject.instance().addMapLayer(vlayer)
            print(f"Successfully added from zip: {layer_name}")
            return

        def first_shp_under(root):
            for r, _, files in os.walk(root):
                for fn in files:
                    if fn.lower().endswith(".shp"):
                        return os.path.join(r, fn)
            return None

        filename_only = os.path.splitext(os.path.basename(zip_path))[0]
        extract_folder = os.path.join(os.path.dirname(zip_path), filename_only)
        shp_file = first_shp_under(extract_folder) if os.path.isdir(extract_folder) else None
        if shp_file is None:
            try:
                os.makedirs(extract_folder, exist_ok=True)
                self._safeExtractZip(zip_path, extract_folder)
            except Exception as e:
                self.iface.messageBar().pushMessage(
                    "Warning", f"Could not read zip: {e}", level=Qgis.Warning
                )
                return
            shp_file = first_shp_under(extract_folder)
        if shp_file:
            self.getBasemap(shp_file)
        else:
            self.iface.messageBar().pushMessage(
                "Warning", "Could not load a shapefile from zip.", level=Qgis.Warning
            )

    
    def _current_border_pen_style(self):
        """Pen style from cmbBorderStyle when populated (Designer / user); else radios."""
        dw = self.dockwidget
        if dw is None:
            return Qt.SolidLine
        combo = getattr(dw, "cmbBorderStyle", None)
        if combo is not None and combo.count() > 0:
            data = combo.currentData()
            if data is not None:
                try:
                    return int(data)
                except (TypeError, ValueError):
                    pass
        if dw.radDashLine.isChecked():
            return Qt.DashLine
        if dw.radSolidLine.isChecked():
            return Qt.SolidLine
        return Qt.SolidLine

    def _on_border_weight_changed(self, value):
        """No line + positive weight is invisible; bump style to Solid when weight is edited."""
        try:
            w = float(value)
        except (TypeError, ValueError):
            w = 0.0
        dw = self.dockwidget
        if dw is not None and w > 0:
            combo = getattr(dw, "cmbBorderStyle", None)
            if combo is not None and hasattr(combo, "currentData"):
                data = combo.currentData()
                try:
                    ps = int(data) if data is not None else None
                except (TypeError, ValueError):
                    ps = None
                if ps == int(Qt.NoPen):
                    idx = combo.findData(int(Qt.SolidLine))
                    if idx < 0:
                        idx = 0
                    combo.blockSignals(True)
                    try:
                        combo.setCurrentIndex(idx)
                    finally:
                        combo.blockSignals(False)
        self.SetSymbolBorders()

    def SetSymbolBorders(self):

        new_color = self.dockwidget.plhQWcolorbutton.color()
        brweight = float(self.dockwidget.dsbBorderWeight.value())

        brstyle = self._current_border_pen_style()
        if brweight == 0:
            brstyle = Qt.NoPen

        layer = self._layerForFormatApply()
        if layer is None:
            self.iface.messageBar().pushMessage(
                "Warning",
                "Select a layer in the panel (or set an active layer) to apply border settings.",
                level=Qgis.Warning,
            )
            return
        renderer = layer.renderer()
        sym = MapestryPluginDockWidget._renderer_primary_symbol(layer)
        if sym is None or sym.symbolLayerCount() < 1:
            return
        symbol_layer = sym.symbolLayer(0)

        if isinstance(symbol_layer, QgsSimpleLineSymbolLayer):
            symbol_layer.setPenStyle(brstyle)
            symbol_layer.setWidth(brweight)
        elif isinstance(symbol_layer, QgsSimpleFillSymbolLayer):
            symbol_layer.setStrokeStyle(brstyle)
            symbol_layer.setStrokeWidth(brweight)
        elif MapestryPluginDockWidget._is_simple_marker_symbol_layer(symbol_layer):
            symbol_layer.setStrokeStyle(brstyle)
            symbol_layer.setStrokeWidth(brweight)
        elif hasattr(renderer, "symbols"):
            symbol_layer.setStrokeStyle(brstyle)
            symbol_layer.setStrokeWidth(brweight)
        if new_color.isValid():
            # Simple line ink is color(), not strokeColor(); strokeColor is for fills/markers outlines.
            if isinstance(symbol_layer, QgsSimpleLineSymbolLayer):
                symbol_layer.setColor(new_color)
            else:
                symbol_layer.setStrokeColor(new_color)

        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())

    def SetSymbolMarkerSize(self):
        """Apply marker size (mm) from the Format tab Size spin box."""
        if self.dockwidget is None:
            return
        dsb = getattr(self.dockwidget, "dsbBorderWeight_5", None)
        if dsb is None:
            return
        size = float(dsb.value())
        # Spin shows blank when value is the sentinel (no marker size for this layer).
        if size < 0:
            return
        layer = self._layerForFormatApply()
        if layer is None:
            return
        if not MapestryPluginDockWidget.apply_marker_size_to_primary_symbol(layer, size):
            return
        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())

    def _on_marker_shape_combo_index_changed(self, idx):
        """MarkerShapeCombo: grid popup updates index without always emitting activated (PyQt5 / QGIS 3.6)."""
        if idx < 0:
            return
        self.SetSymbolMarkerShape()

    def SetSymbolMarkerShape(self):
        """Apply simple marker shape from Format tab Shape combo."""
        if self.dockwidget is None:
            return
        cmb = getattr(self.dockwidget, "cmbMarkerShape", None)
        if cmb is None:
            return
        shape = None
        if hasattr(cmb, "currentMarkerShape"):
            shape = cmb.currentMarkerShape()
        else:
            d = cmb.currentData(Qt.UserRole)
            if d is not None:
                try:
                    shape = coerce_marker_shape_for_setshape(d)
                except Exception:
                    shape = None
        if shape is None:
            return
        layer = self._layerForFormatApply()
        if layer is None:
            return
        if not MapestryPluginDockWidget.apply_marker_shape_to_primary_symbol(layer, shape):
            return
        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())

    def SetSymbolFormat(self):
        self.SetSymbolFill()
        self.SetSymbolBorders()
        self.SetSymbolMarkerSize()
        self.SetSymbolMarkerShape()

    def SetSymbolFill(self):
        """Fill button: polygon fill and/or marker body color (points use same control)."""
        new_color = self.dockwidget.plhQWcolorbutton02.color()
        if not new_color.isValid():
            return
        layer = self._layerForFormatApply()
        if layer is None:
            return
        sym = MapestryPluginDockWidget._renderer_primary_symbol(layer)
        if sym is None or sym.symbolLayerCount() < 1:
            return

        if MapestryPluginDockWidget.apply_marker_fill_color_to_primary_symbol(layer, new_color):
            layer.triggerRepaint()
            iface.layerTreeView().refreshLayerSymbology(layer.id())
            return

        symbol_layer = sym.symbolLayer(0)
        if isinstance(symbol_layer, QgsSimpleLineSymbolLayer):
            return
        if isinstance(symbol_layer, QgsSimpleFillSymbolLayer):
            symbol_layer.setFillColor(new_color)
            layer.triggerRepaint()
            iface.layerTreeView().refreshLayerSymbology(layer.id())
    
    def removeBorders(self):

        """# 1. Get the layer
        layer = QgsProject.instance().mapLayersByName('US Counties 2024')[0]

        # 2. Check the renderer type
        renderer = layer.renderer()

        # If the layer is Categorized (e.g., colored by State Name)
        if renderer.type() == 'categorizedRenderer':
            for category in renderer.categories():
                symbol = category.symbol()
                if symbol:
                    symbol.setStrokeStyle(Qt.NoPen)

        # If the layer is Graduated (e.g., colored by Population density)
        elif renderer.type() == 'graduatedRenderer':
            for ran in renderer.ranges():
                symbol = ran.symbol()
                if symbol:
                    symbol.setStrokeStyle(Qt.NoPen)

        # 3. Apply changes and refresh the map
        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())"""


        layer = self._activeRenderableLayer()
        if layer is None:
            return

       # if layer and layer.geometryType() == QgsWkbTypes.PolygonGeometry:
            # 2. Access the renderer and the first symbol layer (Simple Fill)
        renderer = layer.renderer()
        symbol = renderer.symbol()
        
        # 3. Set StrokeStyle to NoPen to make borders invisible
        #symbol.symbolLayer(0).setStrokeStyle(Qt.NoPen)

        symbol_layer = layer.renderer().symbol().symbolLayer(0)

        if isinstance(symbol_layer, QgsSimpleLineSymbolLayer):
            # CORRECT METHOD
            symbol_layer.setPenStyle(Qt.NoPen)
            symbol_layer.setWidth(0.5)

        elif hasattr(renderer, 'symbols'):
            for symbol in renderer.symbols(QgsRenderContext()):
                symbol.symbolLayer(0).setStrokeStyle(Qt.NoPen)
        
        # 4. Notify QGIS to redraw the map with the new style
        layer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(layer.id())

    
    def amerge_all_shapes(self, input_layer_name):
        """
        Merges all features in a specified layer into a single feature.
        #def merge_all_shapes(input_layer_name, output_file_path=None):
        :param input_layer_name: The name of the layer to process (string).
        :param output_file_path: The path to save the output layer (string). 
                                If None, a temporary layer is created.
        """
        
        # 1. Get the input layer by name
        layers = QgsProject.instance().mapLayersByName(input_layer_name)
        if not layers:
            print(f"Layer '{input_layer_name}' not found.")
            return
        input_layer = layers[0]

        # 2. Define output
        # If no output path is provided, use a temporary layer
        #if output_file_path is None:
        output_destination = 'TEMPORARY_OUTPUT'
        #else:
           #output_destination = output_file_path

        # 3. Define parameters for the 'native:dissolve' algorithm
        # Leaving the 'DISSOLVE_FIELD' parameter blank merges all features
        params = {
            'INPUT': input_layer,
            'FIELD': [],  # Empty list for no dissolve field, merges all features
            'OUTPUT': output_destination
        }

        # 4. Run the processing algorithm
        # processing.runAndLoadResults will load the result into the QGIS interface
        result = processing.runAndLoadResults("native:dissolve", params)
        
        print(f"Successfully dissolved all shapes in '{input_layer_name}'.")
        if output_file_path is None:
            print("Result saved as a temporary layer.")
        else:
            print(f"Result saved to {output_file_path}")

    # --- Example Usage ---
    # Replace 'YourLayerName' with the exact name of your layer in QGIS
    # Optional: specify a save path, e.g., r'C:/temp/merged_shapes.gpkg'



    def load_online_shapefile(url, target_folder, layer_name):
        """
        Downloads a zipped shapefile from a URL, extracts it, and loads it into QGIS.

        :param url: URL of the zipped shapefile.
        :param target_folder: Local folder to save and extract the files.
        :param layer_name: Desired name for the layer in QGIS.
        """
        # Ensure the target folder exists
        if not os.path.exists(target_folder):
            os.makedirs(target_folder)

        # 1. Download the zipped file
        zip_path = os.path.join(target_folder, 'temp_shapefile.zip')
        print(f"Downloading {url} to {zip_path}...")
        try:
            response = requests.get(url)
            response.raise_for_status() # Check for bad request
            with open(zip_path, 'wb') as f:
                f.write(response.content)
            print("Download complete.")
        except requests.exceptions.RequestException as e:
            print(f"Error during download: {e}")
            return

        # 2. Extract the zip file
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(target_folder)
        print(f"Files extracted to {target_folder}.")

        # 3. Find the .shp file in the extracted folder
        shp_file = None
        for root, dirs, files in os.walk(target_folder):
            for file in files:
                if file.endswith('.shp'):
                    shp_file = os.path.join(root, file)
                    break
            if shp_file:
                break

        if shp_file:
            # 4. Load the shapefile into QGIS
            # QgsVectorLayer(dataProviderUri, layerName, providerName)
            layer = QgsVectorLayer(shp_file, layer_name, 'ogr')

            if not layer.isValid():
                print("Layer failed to load!")
            else:
                QgsProject.instance().addMapLayer(layer)
                print(f"Layer '{layer_name}' loaded successfully into QGIS.")
        else:
            print("Could not find a .shp file in the extracted contents.")

        # Optional: Clean up the downloaded zip file
        if os.path.exists(zip_path):
            os.remove(zip_path)

    # --- Example Usage (replace with your URL and details) ---
    # Example URL for a public dataset (Natural Earth airports data)
    #url = "https://naturalearthdata.com"
    # Define your local target folder (e.g., in your Downloads directory)
    target_folder = os.path.join(os.path.expanduser('~'), 'Downloads', 'OnlineShapefile')
    layer_name = "Online_Airports"

    #load_online_shapefile(url, target_folder, layer_name)

    
    def LoadAnyFileAsLayer(self):
        # 1. Define the target URL and local saving directory
        # Example: 2023 Census Tracts for Delaware (FIPS code: '10')
        #https://gadm.org/download_country.html
        #url = "https://www2.census.gov/geo/tiger/TIGER2023/TRACT/tl_2023_10_tract.zip"
        #path = r"C:\Data\Mapping\US_big\cb_2024_us_bg_500k.shp"
        #state - https://www2.census.gov/geo/tiger/TIGER2025/STATE/tl_2025_us_state.zip
        #https://www2.census.gov/geo/tiger/TIGER2025/

        
        url = self.dockwidget.fileLineEdit.text()

        if not url.strip():
            iface.messageBar().pushMessage("Warning", "Please Enter a URL or browse for a file!", level=Qgis.Warning)



        print('url' + url.strip())
        parsed_url = urlparse(url)
        filename_with_extension = os.path.basename(url)
        filename_only = os.path.splitext(filename_with_extension)[0]
        fpath = parsed_url.path
        # Define your plugin's output directory
        plugin_data_dir = os.path.join(os.path.expanduser("~"), "Documents", "QGIS_Census_Data")
        os.makedirs(plugin_data_dir, exist_ok=True)
        zip_path = os.path.join(plugin_data_dir, "temp.zip")



        extract_folder = os.path.join(plugin_data_dir, filename_only)
        # 2. Download the Shapefile Zip from the Census FTP/HTTPS repository
        try:
            print(f"Downloading from {url}...")
            urllib.request.urlretrieve(url, zip_path)
            print("Download complete.")
        except Exception as e:
            print(f"Failed to download file: {e}")
            self.getBasemap(url)
            return

        # 3. Extract the ZIP file
        try:
            self._safeExtractZip(zip_path, extract_folder)
            print(f"Extraction complete to {extract_folder}")
        except Exception as e:
            print(f"Failed to extract zip file: {e}")
            iface.messageBar().pushMessage(
                "Warning", f"Could not extract zip safely: {e}", level=Qgis.Warning
            )
            return

        # 4. Find the .shp file and load it into QGIS
        # Look for the file ending in .shp in the extracted folder
        shp_file = None
        for file in os.listdir(extract_folder):
            if file.endswith(".shp"):
                shp_file = os.path.join(extract_folder, file)
                filelayername = file
                break

        if shp_file:
            # Create the vector layer and add it to the project
            layer_name = filelayername
            vlayer = QgsVectorLayer(shp_file, layer_name, "ogr")
            
            if vlayer.isValid():
                QgsProject.instance().addMapLayer(vlayer)
                print(f"Layer '{layer_name}' successfully added to QGIS!")
            else:
                print("Failed to load the shapefile as a valid QGIS layer.")
        else:
            print("No .shp file found in the extracted directory.")
        
    def FileNamePlain(self, file_path):
        parsed_url = urlparse(file_path)
        filename_with_extension = os.path.basename(file_path)
        filename_only = os.path.splitext(filename_with_extension)[0]
        return filename_only
    

    def AddLabels(self):
        
        label_field = "NAME"

        layer = iface.activeLayer()

        if layer and layer.type() == QgsMapLayer.VectorLayer:
            # 2. Define label settings
            settings = QgsPalLayerSettings()
            
            # Enable labeling
            settings.enabled = True
            
            # Set the field to use for labels (replace 'your_field_name' with the actual field name)
            settings.fieldName = label_field
            
            # Configure text format (font, size, color, etc.)
            text_format = QgsTextFormat()
            text_format.setFont(QFont("Arial", 10))
            text_format.setSize(10)
            # text_format.setColor(QColor(0, 0, 0)) # Uncomment to set text color
            settings.setFormat(text_format)
            
            # Set placement (e.g., around points, on lines)
            # Common options: QgsPalLayerSettings.AroundPoint, QgsPalLayerSettings.Line, QgsPalLayerSettings.OffsetFromPoint
            settings.placement = QgsPalLayerSettings.AroundPoint #

            # Optional: Configure a text buffer for better visibility
            settings.drawTextBuffer = True
            settings.bufferColor = QColor("white")
            settings.bufferSize = 1
            
            # Optional: If using an expression for labels, set isExpression to True
            # settings.isExpression = True #

            # 3. Apply labeling to the layer
            labeler = QgsVectorLayerSimpleLabeling(settings)
            layer.setLabelsEnabled(True)
            layer.setLabeling(labeler)

            # 4. Refresh the map canvas to display the changes
            iface.mapCanvas().refresh()
            print(f"Labels enabled for layer: {layer.name()}")
        else:
            print("No active vector layer found.")

    def _ensure_geocoder(self):
        """One MapTilerGeocoder for the plugin lifetime so pending replies are not orphaned."""
        if self.geocoder is not None:
            return
        parent = self.dockwidget if self.dockwidget is not None else self.iface.mainWindow()
        self.geocoder = MapTilerGeocoder("nYiSyC7exzAVlT4JiseG", parent)
        self.geocoder.resultReady.connect(self.onGeocodeSuccess)
        self.geocoder.errorOccurred.connect(self.onGeocodeError)

    def openPointMapDialog(self):
        """Show Add points dialog — same pattern as openNewMapDialog (non-modal, parent = main window)."""
        if self._point_map_dialog is None:
            self._point_map_dialog = PointMapDialog(self, self.iface.mainWindow())
        self._point_map_dialog.show()
        self._point_map_dialog.raise_()
        self._point_map_dialog.activateWindow()

    def openRouteConnectionsDialog(self):
        """Vendored Route Connections UI (`vendor/route_connections`); updates when you replace that tree."""
        try:
            from .vendor.route_connections.route_connections import RouteConnections
        except ImportError as e:
            self.iface.messageBar().pushMessage(
                "Mapestry",
                f"Could not load Route Connections: {e}",
                level=Qgis.Critical,
            )
            return
        if self._route_connections_host is None:
            host = RouteConnections(self.iface)
            # Patch before first run() wires mApplyButton → sync_arcs (keeps vendor tree clean for upgrades).
            orig_sync = host.sync_arcs
            plugin = self

            def _wrapped_sync():
                dlg = host.dialog
                if dlg is None or not dlg.current_layer:
                    return orig_sync()
                n = dlg.mConnectionsTable.rowCount()
                orig_sync()
                if n > 0:
                    plugin.register_completed_tool("airline_route")

            host.sync_arcs = _wrapped_sync
            self._route_connections_host = host
        self._route_connections_host.run()

    def register_completed_tool(self, slug):
        """Add a catalog tool to dock Active Tools once the user completes its wizard."""
        dw = self.dockwidget
        if dw is not None and hasattr(dw, "register_completed_tool"):
            dw.register_completed_tool(slug)

    def runGeocodingFromDialog(self, dlg):
        """Read addresses + point color from point_map.ui; layer color comes from _geocode_color_widget."""
        text = dlg.tedAddresses.toPlainText().strip()
        if not text:
            self.iface.messageBar().pushMessage(
                "Warning", "Enter at least one address.", level=Qgis.Warning
            )
            return

        addresses = [line.strip() for line in text.split("\n") if line.strip()]
        if not addresses:
            self.iface.messageBar().pushMessage(
                "Warning", "Enter at least one valid address line.", level=Qgis.Warning
            )
            return

        self._geocode_color_widget = getattr(dlg, "plhQGSCB03", None)

        try:
            self._ensure_geocoder()
            for addr in addresses:
                self.geocoder.geocode(addr)
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "Geocode Error", f"Could not start geocoding: {e}", level=Qgis.Critical
            )

    def onGeocodeSuccess(self, address, lon, lat):
        print(f"{address} → {lon}, {lat}")

        # Example: add a point to QGIS
        layer = QgsProject.instance().mapLayersByName("Geocoded Points")
        if layer:
            layer = layer[0]
        else:
            layer = QgsVectorLayer("Point?crs=EPSG:4326", "Geocoded Points", "memory")
            symbol = layer.renderer().symbol()
            color_btn = getattr(self, "_geocode_color_widget", None)
            if color_btn is not None:
                color_picked = color_btn.color()
            else:
                color_picked = QColor(200, 60, 60)
            symbol.setColor(QColor(color_picked))
            layer.triggerRepaint()
            pr = layer.dataProvider()
            pr.addAttributes([
                QgsField("address", QVariant.String)
            ])
            layer.updateFields()
            QgsProject.instance().addMapLayer(layer)

        pr = layer.dataProvider()
        feat = QgsFeature(layer.fields())
        feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(lon, lat)))
        feat["address"] = address
        pr.addFeature(feat)
        layer.triggerRepaint()

    def onGeocodeError(self, address, message):
        print(f"Error geocoding '{address}': {message}")
        self.iface.messageBar().pushMessage(
            "Geocode Error", f"{address}: {message}", level=Qgis.Warning
        )



        

